/*
 * This header is generated by classdump-dyld 1.0
 * on Monday, March 13, 2023 at 2:12:23 AM Eastern European Standard Time
 * Operating System: Version 16.3 (Build 20D47)
 * Image Source: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */

@protocol SBMesaUnlockTriggerDelegate;
@interface SBMesaUnlockTrigger : NSObject
{

	id<SBMesaUnlockTriggerDelegate> _delegate;
	BOOL _authenticated;
}

- (void)screenOn;
- (BOOL)authenticated;
- (void)setDelegate:(id<SBMesaUnlockTriggerDelegate>)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (void)setAuthenticated:(BOOL)arg1;
- (id<SBMesaUnlockTriggerDelegate>)delegate;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)description;
- (void)screenOff;
- (void)fingerOn;
- (BOOL)bioUnlock;
- (void)significantUserInteractionOccurred;
- (void)menuButtonDown;
- (void)menuButtonUp;
- (void)fingerOff;
- (void)lockButtonDown;
@end
