name: Theos CI

on:
  release:
    types:
      - created

jobs:
  build:
    permissions:
      contents: write
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Theos Setup (Setup)
        uses: NyaMisty/theos-action@master

      - name: Build Release package - Rootful
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          make clean
          make package FINALPACKAGE=1

      - name: Build Release package - Rootless
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          make clean
          make package THEOS_PACKAGE_SCHEME=rootless FINALPACKAGE=1

      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          files: |
            ${{ github.workspace }}/packages/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
